blank_issues_enabled: true
contact_links:
    - name: â“ FAQ and Basic User Guide
      url: https://gloomhaven.kenwanderers.com/help
      about: A Small FAQ and basic guide how to use Kenwanderer Haven
    - name: ğŸ’¡ General Ideas, Feedback and Questions
      url: https://github.com/Kenwanderers/kenwandererhaven/discussions
      about: To discuss ideas, give general feedback or asking for help just use the GitHub Discussion