blank_issues_enabled: true
contact_links:
    - name: â“ FAQ and Basic User Guide
      url: https://help.gloomhaven-secretariat.de/
      about: A Small FAQ and basic guide how to use Gloomhaven Secretariat
    - name: ğŸ’¡ General Ideas, Feedback and Questions
      url: https://github.com/Lurkars/gloomhavensecretariat/discussions
      about: To discuss ideas, give general feedback or asking for help just use the GitHub Discussion